language: python
python: 3.6

install:
  - pip install mkdocs
  - git clone https://github.com/mindbender-studio/core.git

script:
  - pip install -r requirements.txt;
  - PYTHONPATH=$CD/core python build.py
  - mkdocs build

before_deploy:
  - cd site

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
