language: python
python: 3.6

install:
  - pip install -r requirements.txt;
  - git clone https://github.com/getavalon/core.git

script:
  - PYTHONPATH=$(pwd)/core python _build.py
  - mkdocs build
  - export OUTPUT=$(pwd)/site

before_deploy:
  - cd $OUTPUT
  - touch .nojekyll

deploy:
  - provider: pages
    skip_cleanup: true
    local-dir: site
    github_token: $GITHUB_TOKEN
    repo: getavalon/getavalon.github.io
    target_branch: master

  # Backwards compatibility
  - provider: pages
    skip_cleanup: true
    local-dir: site
    github_token: $GITHUB_TOKEN
    repo: mindbender-studio/mindbender-studio.github.io
    target_branch: master
