language: python
python: 3.6

install:
- pip install mkdocs

script:
  - pip install -r requirements.txt;
  - mkdocs build

before_deploy:
  - cd site

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
