language: python
python: 3.6

install:
  - pip install -r requirements.txt;
  - git clone https://github.com/getavalon/core.git

script:
  - PYTHONPATH=$(pwd)/core python build.py
  - mkdocs build

before_deploy:
  - cd site
  - touch .nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: getavalon/getavalon.github.io
  target_branch: master
  on:
    branch: master