# Project information
site_name: Avalon
site_description: A global production pipeline for film and games
site_author: Marcus Ottosson
site_url: http://getavalon.github.io

# Repository
repo_name: avalon/core
repo_url: https://github.com/getavalon/core

# Copyright
copyright: "Copyright &copy; 2017 Marcus Ottosson"

# Page tree
pages:
  - Home: index.md
  - "1.0":
    - " ": 1.0/index.md
  - "2.0":
    - " ": 2.0/index.md
    # - Introduction: 2.0/introduction.md
    - Overview: 2.0/overview.md
    - Guides: 2.0/guides.md
    - Tutorials: 2.0/tutorials.md
    - Reference: 2.0/reference.md
    - Tools: 2.0/tools.md
    - Glossary: 2.0/glossary.md
  - Polly:
    - Home: polly/index.md
    - Assets: polly/assets.md
    - Tutorials: polly/tutorials.md
  - Colorbleed:
    - Home: colorbleed/index.md

# Theme directory
theme_dir: theme
docs_dir: build

# Options
extra:
  logo: assets/images/logo.png
  feature:
    tabs: true
  palette:
    primary: light blue
    accent: light blue
  font: false
  social:
    - type: globe
      link: http://getavalon.github.io
    - type: github-alt
      link: https://github.com/getavalon
    - type: linkedin
      link: https://linkedin.com/in/marcusottosson

# Extensions
markdown_extensions:
  - markdown.extensions.extra
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# Google Analytics
google_analytics:
  - "UA-101505233-1"
  - auto
