# Project information
site_name: Avalon
site_description: A global production pipeline for film and games
site_author: Marcus Ottosson
# site_url: http://getavalon.github.io/docs

# Repository
repo_name: avalon/core
repo_url: https://github.com/getavalon/core

# Copyright
copyright: "Copyright &copy; 2017 Marcus Ottosson"

# Page tree
pages:
  - Home: index.md
  - "1.0":
    - " ": 1.0/index.md
  - "2.0":
    - " ": 2.0/index.md
    - Introduction: 2.0/introduction.md
    - Overview: 2.0/overview.md
    - Tutorials: 2.0/tutorials.md
    - How To: 2.0/howto.md
    - Topic Guides: 2.0/guides.md
    - Reference: 2.0/reference.md
  - Polly:
    - Home: polly/index.md
    - Assets: polly/assets.md
  - Colorbleed:
    - Home: colorbleed/index.md

# Theme directory
theme_dir: theme
docs_dir: pages
extra_css:
  - "css/extra.css"
extra_javascript:
  - "js/extra.js"

# Options
extra:
  logo: assets/images/logo.png
  feature:
    tabs: true
  palette:
    primary: light blue
    accent: light blue
  font: false
  social:
    - type: globe
      link: http://avalon.com
    - type: github-alt
      link: https://github.com/getavalon
    - type: twitter
      link: https://twitter.com/marcusottosson
    - type: linkedin
      link: https://linkedin.com/in/marcusottosson

# Extensions
markdown_extensions:
  - meta
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false, linenums=true)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto